### ISSUE TITLE
Static Site example

### ISSUE THREAD

**Issue by jaybe-jekyll** [jgm/select-meta#1]
Hi @jgm 

Have been playing with `select-meta` and it is interesting and exciting to consider the possibilities.

Would it be possible to provide an example of a static site scenario with `select-meta`?

I have been trying to "port" `yst` in functionality over to `select-meta` however I've had limited success assuredly due to inexperience.

**Comment by jgm** [comment]
I haven't used it for this yet, but the idea was indeed to allow you to replace most of what yst does.
I don't have an example yet. Maybe you can provide one.

**Comment by jaybe-jekyll** [comment]
I intend to keep working on it and learning. If and when I have some reasonable successes I will be happy to share as a starting point.

**Comment by jaybe-jekyll** [comment]
Explaining some thoughts and approaches to vet my thinking and if reasonable- how to go about implementing.

My ideas include separating--
- Content (purely content only; no meta within; a "clean" content document (in markdown))
  - e.g. `unique_content_file.md`
- Meta for the/it's associated content.
  - e.g. `unique_content_file__meta.yaml`
- Layout/template for meta'd content-- a default or otherwise unique template.
  - e.g. default_unique_content__template.html.st

> The goal and thinking are to separate purely content from its meta from its layout and presentation.

Building the meta with `meta-select.lua` is successful (and awesome).

However, the meta produced is (I believe) a `map`... which is formatted such as:

```yaml
---
glaces:
- items:
  - introduced: '2009-04-30'
    name: Chocolate
    type: traditional
  type: traditional
- items:
  - introduced: '2015-03-15'
    name: Dark Chocolate
    type: gelato
  type: gelato
- items:
  - introduced: '2010-01-01'
    name: Melon
    type: sorbet
  - introduced: '2011-03-03'
    name: Peach
    type: sorbet
  type: sorbet
lang: 'fr-FR'
new:
- items:
  - introduced: '2009-04-30'
    name: Chocolate
    type: traditional
  - introduced: '2015-03-15'
    name: Dark Chocolate
    type: gelato
  - introduced: '2010-01-01'
    name: Melon
    type: sorbet
---
```

Reiterating, one of the thoughts/goals is to *produce* usable common YAML frontmatter (i.e. title, author, date, etc.) for a unique content file- leveraging that built common meta.

As above, however, this data seems structured in a way that only seems suitable, with my current knowledge, as data for within the content- say via the string templates.

I am able to extract individual aspects of the metadata explicitly-

e.g.

```javascript
$for(glaces)$
  $for(it.items)$
    $it.name$
  $endfor$
$endfor$
```

That anticipates *knowing* what the meta will be and explicitly extracting it.

Is it reasonable and possible to structure and or access the produced select-meta in a way that would allow such a concept?

Opinions on the concept in general are welcome as well.  I like the idea of full separation of content/writing in `md` from its [potentially-changing] meta- and its structured template.

edit: words/clarity
